### ISSUE TITLE
Создать html страницы регистрации

### ISSUE THREAD

**Issue by AnnPkGit** [AnnPkGit/WEB-coursework#12]

**Comment by pallyh** [comment]
![Image](https://user-images.githubusercontent.com/85061890/210135682-5d25d555-a47f-4bc1-b109-f3a83d3e597f.png)

**Comment by pallyh** [comment]
если что есть ещё файл с 

![Image](https://user-images.githubusercontent.com/85061890/210141213-6f6df2af-a465-405b-adff-24ccaafccbb9.png)

**Comment by AnnPkGit** [comment]
оставила пару комментов на ПР
